- name: install httpd (Ubuntu)
  apt:
    name: apache2
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: start apache (Ubuntu)
  service:
    name: apache2
    state: restarted
  when: ansible_distribution == "Ubuntu"

- name: install httpd (CentOS)
  yum:
    name: httpd
    state: latest
  when: ansible_distribution == "CentOS"

- name: start httpd (CentOS)
  service:
    name: httpd
    state: restarted
  when: ansible_distribution == "CentOS"

- name: start httpd (Ubuntu)
  service:
    name: apache2
    state: restarted
  when: ansible_distribution == "Ubuntu"

- name: install mariadb (Ubuntu & CentOS)
  package:
     name: mariadb-server
     state: latest

- name: start mariadb
  service:
    name: mariadb
    state: restarted
    enabled: true

- name: install php
  package:
    name: php
    state: latest
